# Setup
title:               창순 Blog
tagline:             'Backend Developer'
description:         'github: https://github.com/Ghosttrio'
url:                 https://ghosttrio.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Changsoon Park
  url:               
  email:             ghosttrio.mail@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
